import { FastSalesCategory, FastSalesCustomer, FastSalesProduct } from './FastSalesTypes';

export const MOCK_CATEGORIES: FastSalesCategory[] = [
  { id: 0, name: 'Tất cả' },
  { id: 1, name: 'Thực phẩm' },
  { id: 2, name: 'Đồ uống' },
  { id: 3, name: 'Gia vị' },
  { id: 4, name: 'Hóa mỹ phẩm' },
];

export const MOCK_PRODUCTS: FastSalesProduct[] = [
  {
    id: 101,
    productCode: 'SP001',
    productName: 'Sữa tươi tiệt trùng Vinamilk 1L',
    categoryId: 2,
    categoryName: 'Đồ uống',
    unitName: 'Hộp',
    salePrice: 38000,
    quantityOnHand: 45,
    status: 'ACTIVE',
  },
  {
    id: 102,
    productCode: 'SP002',
    productName: 'Gạo Tám Thơm ST25 5kg',
    categoryId: 1,
    categoryName: 'Thực phẩm',
    unitName: 'Bao',
    salePrice: 195000,
    quantityOnHand: 18,
    status: 'ACTIVE',
  },
  {
    id: 103,
    productCode: 'SP003',
    productName: 'Nước mắm Nam Ngư 750ml',
    categoryId: 3,
    categoryName: 'Gia vị',
    unitName: 'Chai',
    salePrice: 42000,
    quantityOnHand: 60,
    status: 'ACTIVE',
  },
  {
    id: 104,
    productCode: 'SP004',
    productName: 'Bột giặt OMA Chuyên Dụng 3kg',
    categoryId: 4,
    categoryName: 'Hóa mỹ phẩm',
    unitName: 'Túi',
    salePrice: 135000,
    quantityOnHand: 8,
    status: 'ACTIVE',
  },
  {
    id: 105,
    productCode: 'SP005',
    productName: 'Dầu ăn Tường An Gold 1L',
    categoryId: 3,
    categoryName: 'Gia vị',
    unitName: 'Chai',
    salePrice: 52000,
    quantityOnHand: 25,
    status: 'ACTIVE',
  },
  {
    id: 106,
    productCode: 'SP006',
    productName: 'Bánh bơ trứng Cosy 300g',
    categoryId: 1,
    categoryName: 'Thực phẩm',
    unitName: 'Hộp',
    salePrice: 48000,
    quantityOnHand: 0, // Hết hàng để test UI out-of-stock
    status: 'ACTIVE',
  },
  {
    id: 107,
    productCode: 'SP007',
    productName: 'Cà phê hòa tan G7 3in1 (21 gói)',
    categoryId: 2,
    categoryName: 'Đồ uống',
    unitName: 'Hộp',
    salePrice: 68000,
    quantityOnHand: 30,
    status: 'ACTIVE',
  },
  {
    id: 108,
    productCode: 'SP008',
    productName: 'Nước rửa chén Sunlight Chanh 750ml',
    categoryId: 4,
    categoryName: 'Hóa mỹ phẩm',
    unitName: 'Chai',
    salePrice: 32000,
    quantityOnHand: 3, // Sắp hết hàng để test low stock
    status: 'ACTIVE',
  },
];

export const MOCK_CUSTOMERS: FastSalesCustomer[] = [
  {
    id: 201,
    customerCode: 'KH001',
    customerName: 'Nguyễn Văn An',
    phone: '0912 345 678',
    debtBalance: 450000,
    creditLimit: 5000000,
  },
  {
    id: 202,
    customerCode: 'KH002',
    customerName: 'Trần Thị Bình',
    phone: '0987 654 321',
    debtBalance: 0,
    creditLimit: 10000000,
  },
  {
    id: 203,
    customerCode: 'KH003',
    customerName: 'Cửa hàng Tạp Hóa Cường Phát',
    phone: '0903 111 222',
    debtBalance: 2400000,
    creditLimit: 15000000,
  },
];
