-- HBDT Platform
-- V001: canonical empty schema containing all 33 application tables.
-- The database itself is provisioned by MySQL/Docker; Flyway owns the tables.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `accounting_book_entries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `accounting_book_id` bigint unsigned NOT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `entry_no` int unsigned NOT NULL,
  `entry_date` date NOT NULL,
  `source_type` varchar(40) NOT NULL,
  `source_id` bigint unsigned DEFAULT NULL,
  `document_number` varchar(100) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `entry_data` json NOT NULL,
  `entry_status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `reverses_entry_id` bigint unsigned DEFAULT NULL,
  `adjustment_reason` varchar(1000) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_accounting_book_entries_number` (`accounting_book_id`,`entry_no`),
  KEY `idx_accounting_book_entries_date` (`accounting_book_id`,`entry_date`),
  KEY `idx_accounting_book_entries_source` (`source_type`,`source_id`),
  KEY `idx_accounting_book_entries_created_by` (`created_by`),
  KEY `idx_accounting_book_entries_reverses` (`reverses_entry_id`),
  CONSTRAINT `fk_accounting_book_entries_book` FOREIGN KEY (`accounting_book_id`) REFERENCES `accounting_books` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_book_entries_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_book_entries_reverses` FOREIGN KEY (`reverses_entry_id`) REFERENCES `accounting_book_entries` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_accounting_book_entries_number` CHECK ((`entry_no` > 0)),
  CONSTRAINT `chk_accounting_book_entries_source_type` CHECK ((`source_type` in (_utf8mb4'SALES_ORDER',_utf8mb4'STOCK_IMPORT',_utf8mb4'DEBT_TRANSACTION',_utf8mb4'INVENTORY_TRANSACTION',_utf8mb4'TAX_OBLIGATION',_utf8mb4'TAX_PAYMENT',_utf8mb4'MANUAL_ADJUSTMENT',_utf8mb4'OPENING_BALANCE'))),
  CONSTRAINT `chk_accounting_book_entries_status` CHECK ((`entry_status` in (_utf8mb4'ACTIVE',_utf8mb4'REVERSED',_utf8mb4'VOIDED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `accounting_books` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `template_version_id` bigint unsigned NOT NULL,
  `book_code` varchar(50) NOT NULL,
  `book_name` varchar(255) NOT NULL,
  `period_from` date NOT NULL,
  `period_to` date NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'OPEN',
  `opened_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `closed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_accounting_books_business_period` (`business_id`,`book_code`,`period_from`,`period_to`),
  KEY `idx_accounting_books_business_period` (`business_id`,`period_from`,`period_to`),
  KEY `idx_accounting_books_template_version` (`template_version_id`),
  CONSTRAINT `fk_accounting_books_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_accounting_books_template_version` FOREIGN KEY (`template_version_id`) REFERENCES `report_template_versions` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_accounting_books_period` CHECK ((`period_to` >= `period_from`)),
  CONSTRAINT `chk_accounting_books_status` CHECK ((`status` in (_utf8mb4'OPEN',_utf8mb4'CLOSED',_utf8mb4'VOIDED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ai_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `requested_by` bigint unsigned NOT NULL,
  `sales_order_id` bigint unsigned DEFAULT NULL,
  `input_type` varchar(20) NOT NULL,
  `raw_text` text,
  `audio_url` varchar(500) DEFAULT NULL,
  `extracted_data` json DEFAULT NULL,
  `confidence_score` decimal(5,4) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'RECEIVED',
  `error_message` varchar(1000) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` datetime DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_requests_sales_order` (`sales_order_id`),
  KEY `idx_ai_requests_business_created_at` (`business_id`,`created_at`),
  KEY `idx_ai_requests_requested_by` (`requested_by`),
  KEY `idx_ai_requests_status` (`business_id`,`status`),
  CONSTRAINT `fk_ai_requests_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_ai_requests_requested_by` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_ai_requests_sales_order` FOREIGN KEY (`sales_order_id`) REFERENCES `sales_orders` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_ai_requests_confidence` CHECK (((`confidence_score` is null) or (`confidence_score` between 0 and 1))),
  CONSTRAINT `chk_ai_requests_input_type` CHECK ((`input_type` in (_utf8mb4'TEXT',_utf8mb4'VOICE'))),
  CONSTRAINT `chk_ai_requests_status` CHECK ((`status` in (_utf8mb4'RECEIVED',_utf8mb4'PROCESSING',_utf8mb4'COMPLETED',_utf8mb4'FAILED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `announcements` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_by` bigint unsigned DEFAULT NULL,
  `target_role_id` bigint unsigned DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `audience_type` varchar(20) NOT NULL DEFAULT 'ALL_USERS',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `published_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_announcements_status_published` (`status`,`published_at`),
  KEY `idx_announcements_created_by` (`created_by`),
  KEY `idx_announcements_target_role` (`target_role_id`),
  CONSTRAINT `fk_announcements_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_announcements_target_role` FOREIGN KEY (`target_role_id`) REFERENCES `roles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_announcements_audience_type` CHECK ((`audience_type` in (_utf8mb4'ALL_USERS',_utf8mb4'SPECIFIC_ROLE'))),
  CONSTRAINT `chk_announcements_period` CHECK (((`expires_at` is null) or (`published_at` is null) or (`expires_at` >= `published_at`))),
  CONSTRAINT `chk_announcements_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'PUBLISHED',_utf8mb4'ARCHIVED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `audit_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned DEFAULT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `action` varchar(100) NOT NULL,
  `entity_type` varchar(100) NOT NULL,
  `entity_id` bigint unsigned DEFAULT NULL,
  `old_data` json DEFAULT NULL,
  `new_data` json DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_audit_logs_business_created_at` (`business_id`,`created_at`),
  KEY `idx_audit_logs_user_created_at` (`user_id`,`created_at`),
  KEY `idx_audit_logs_entity` (`entity_type`,`entity_id`),
  KEY `idx_audit_logs_action_created_at` (`action`,`created_at`),
  CONSTRAINT `fk_audit_logs_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_logs_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `businesses` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_code` varchar(30) NOT NULL,
  `business_name` varchar(255) NOT NULL,
  `owner_name` varchar(150) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `tax_code` varchar(20) DEFAULT NULL,
  `inventory_valuation_method` varchar(30) NOT NULL DEFAULT 'PERIODIC_WEIGHTED_AVERAGE',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `logo_object_key` varchar(500) DEFAULT NULL,
  `cover_image_object_key` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_businesses_business_code` (`business_code`),
  UNIQUE KEY `uk_businesses_tax_code` (`tax_code`),
  CONSTRAINT `chk_businesses_inventory_valuation_method` CHECK ((`inventory_valuation_method` in (_utf8mb4'PERIODIC_WEIGHTED_AVERAGE',_utf8mb4'FIFO')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `categories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `category_code` varchar(30) NOT NULL,
  `category_name` varchar(150) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_categories_business_code` (`business_id`,`category_code`),
  KEY `idx_categories_business` (`business_id`),
  CONSTRAINT `fk_categories_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `customers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `customer_code` varchar(50) NOT NULL,
  `customer_name` varchar(150) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `note` varchar(500) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customers_business_code` (`business_id`,`customer_code`),
  KEY `idx_customers_business_name` (`business_id`,`customer_name`),
  KEY `idx_customers_business_phone` (`business_id`,`phone`),
  CONSTRAINT `fk_customers_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_customers_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'INACTIVE')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `debt_transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `customer_id` bigint unsigned NOT NULL,
  `sales_order_id` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `transaction_code` varchar(50) DEFAULT NULL,
  `transaction_type` varchar(30) NOT NULL,
  `amount` decimal(18,2) NOT NULL,
  `payment_method` varchar(30) DEFAULT NULL,
  `reference_number` varchar(100) DEFAULT NULL,
  `transaction_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `balance_after` decimal(18,2) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_debt_transactions_business_code` (`business_id`,`transaction_code`),
  KEY `fk_debt_transactions_customer` (`customer_id`),
  KEY `idx_debt_transactions_customer_date` (`business_id`,`customer_id`,`created_at`),
  KEY `idx_debt_transactions_sales_order` (`sales_order_id`),
  KEY `idx_debt_transactions_created_by` (`created_by`),
  KEY `idx_debt_transactions_business_transaction_date` (`business_id`,`transaction_date`),
  CONSTRAINT `fk_debt_transactions_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_debt_transactions_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_debt_transactions_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_debt_transactions_sales_order` FOREIGN KEY (`sales_order_id`) REFERENCES `sales_orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_debt_transactions_amount` CHECK ((`amount` > 0)),
  CONSTRAINT `chk_debt_transactions_balance` CHECK ((`balance_after` >= 0)),
  CONSTRAINT `chk_debt_transactions_type` CHECK ((`transaction_type` in (_utf8mb4'DEBT_CREATED',_utf8mb4'PAYMENT_RECEIVED',_utf8mb4'ADJUSTMENT_INCREASE',_utf8mb4'ADJUSTMENT_DECREASE',_utf8mb4'ORDER_CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `feedback` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `submitted_by` bigint unsigned NOT NULL,
  `resolved_by` bigint unsigned DEFAULT NULL,
  `feedback_type` varchar(30) NOT NULL DEFAULT 'FEEDBACK',
  `subject` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'OPEN',
  `admin_response` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `resolved_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_feedback_business_status` (`business_id`,`status`,`created_at`),
  KEY `idx_feedback_submitted_by` (`submitted_by`),
  KEY `idx_feedback_resolved_by` (`resolved_by`),
  CONSTRAINT `fk_feedback_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_feedback_resolved_by` FOREIGN KEY (`resolved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_feedback_submitted_by` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_feedback_status` CHECK ((`status` in (_utf8mb4'OPEN',_utf8mb4'IN_PROGRESS',_utf8mb4'RESOLVED',_utf8mb4'CLOSED'))),
  CONSTRAINT `chk_feedback_type` CHECK ((`feedback_type` in (_utf8mb4'FEEDBACK',_utf8mb4'COMPLAINT',_utf8mb4'INCIDENT')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `generated_reports` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `template_version_id` bigint unsigned NOT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `reviewed_by` bigint unsigned DEFAULT NULL,
  `reporting_period_from` date NOT NULL,
  `reporting_period_to` date NOT NULL,
  `generation_no` int unsigned NOT NULL DEFAULT '1',
  `generation_method` varchar(20) NOT NULL DEFAULT 'SYSTEM',
  `report_data` json NOT NULL,
  `file_url` varchar(500) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `rejection_reason` varchar(1000) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `reviewed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_generated_reports_generation` (`business_id`,`template_version_id`,`reporting_period_from`,`reporting_period_to`,`generation_no`),
  KEY `idx_generated_reports_business_period` (`business_id`,`reporting_period_from`,`reporting_period_to`),
  KEY `idx_generated_reports_status` (`business_id`,`status`),
  KEY `idx_generated_reports_template_version` (`template_version_id`),
  KEY `idx_generated_reports_created_by` (`created_by`),
  KEY `idx_generated_reports_reviewed_by` (`reviewed_by`),
  CONSTRAINT `fk_generated_reports_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_generated_reports_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_generated_reports_reviewed_by` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_generated_reports_template_version` FOREIGN KEY (`template_version_id`) REFERENCES `report_template_versions` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_generated_reports_generation_method` CHECK ((`generation_method` in (_utf8mb4'SYSTEM',_utf8mb4'AI'))),
  CONSTRAINT `chk_generated_reports_generation_no` CHECK ((`generation_no` > 0)),
  CONSTRAINT `chk_generated_reports_period` CHECK ((`reporting_period_to` >= `reporting_period_from`)),
  CONSTRAINT `chk_generated_reports_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'APPROVED',_utf8mb4'REJECTED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_balances` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `quantity_on_hand` decimal(18,3) NOT NULL DEFAULT '0.000',
  `average_unit_cost` decimal(18,2) NOT NULL DEFAULT '0.00',
  `inventory_value` decimal(18,2) NOT NULL DEFAULT '0.00',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_inventory_balances_business_product` (`business_id`,`product_id`),
  KEY `idx_inventory_balances_product` (`product_id`),
  CONSTRAINT `fk_inventory_balances_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_balances_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_inventory_balances_average_unit_cost` CHECK ((`average_unit_cost` >= 0)),
  CONSTRAINT `chk_inventory_balances_inventory_value` CHECK ((`inventory_value` >= 0)),
  CONSTRAINT `chk_inventory_balances_quantity` CHECK ((`quantity_on_hand` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `inventory_transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `transaction_type` varchar(30) NOT NULL,
  `reference_type` varchar(30) DEFAULT NULL,
  `reference_id` bigint unsigned DEFAULT NULL,
  `quantity_change` decimal(18,3) NOT NULL,
  `balance_after` decimal(18,3) NOT NULL,
  `unit_cost` decimal(18,2) DEFAULT NULL,
  `transaction_value` decimal(18,2) DEFAULT NULL,
  `balance_value` decimal(18,2) DEFAULT NULL,
  `cost_status` varchar(20) NOT NULL DEFAULT 'PROVISIONAL',
  `costed_at` datetime DEFAULT NULL,
  `note` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_inventory_transactions_product` (`product_id`),
  KEY `idx_inventory_transactions_product_date` (`business_id`,`product_id`,`created_at`),
  KEY `idx_inventory_transactions_reference` (`reference_type`,`reference_id`),
  KEY `idx_inventory_transactions_created_by` (`created_by`),
  KEY `idx_inventory_transactions_cost_status` (`business_id`,`cost_status`,`created_at`),
  CONSTRAINT `fk_inventory_transactions_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_transactions_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_transactions_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_inventory_transactions_balance` CHECK ((`balance_after` >= 0)),
  CONSTRAINT `chk_inventory_transactions_balance_value` CHECK (((`balance_value` is null) or (`balance_value` >= 0))),
  CONSTRAINT `chk_inventory_transactions_change` CHECK ((`quantity_change` <> 0)),
  CONSTRAINT `chk_inventory_transactions_cost_status` CHECK ((`cost_status` in (_utf8mb4'PROVISIONAL',_utf8mb4'FINAL'))),
  CONSTRAINT `chk_inventory_transactions_transaction_value` CHECK (((`transaction_value` is null) or (`transaction_value` >= 0))),
  CONSTRAINT `chk_inventory_transactions_type` CHECK ((`transaction_type` in (_utf8mb4'STOCK_IMPORT',_utf8mb4'SALE',_utf8mb4'ORDER_CANCEL',_utf8mb4'ADJUSTMENT_IN',_utf8mb4'ADJUSTMENT_OUT'))),
  CONSTRAINT `chk_inventory_transactions_unit_cost` CHECK (((`unit_cost` is null) or (`unit_cost` >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notifications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `ai_request_id` bigint unsigned DEFAULT NULL,
  `sales_order_id` bigint unsigned DEFAULT NULL,
  `notification_type` varchar(40) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `read_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_user_unread` (`user_id`,`is_read`,`created_at`),
  KEY `idx_notifications_business` (`business_id`,`created_at`),
  KEY `idx_notifications_ai_request` (`ai_request_id`),
  KEY `idx_notifications_sales_order` (`sales_order_id`),
  CONSTRAINT `fk_notifications_ai_request` FOREIGN KEY (`ai_request_id`) REFERENCES `ai_requests` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_notifications_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_notifications_sales_order` FOREIGN KEY (`sales_order_id`) REFERENCES `sales_orders` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_notifications_type` CHECK ((`notification_type` in (_utf8mb4'AI_DRAFT_CREATED',_utf8mb4'ORDER_STATUS_CHANGED',_utf8mb4'GENERAL')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_prices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `product_unit_id` bigint unsigned NOT NULL,
  `minimum_quantity` decimal(18,3) NOT NULL DEFAULT '1.000',
  `sale_price` decimal(18,2) NOT NULL,
  `effective_from` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `effective_to` datetime DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_prices_rule` (`product_unit_id`,`minimum_quantity`,`effective_from`),
  KEY `idx_product_prices_product_unit` (`product_unit_id`),
  CONSTRAINT `fk_product_prices_product_unit` FOREIGN KEY (`product_unit_id`) REFERENCES `product_units` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `chk_product_prices_effective_period` CHECK (((`effective_to` is null) or (`effective_to` >= `effective_from`))),
  CONSTRAINT `chk_product_prices_minimum_quantity` CHECK ((`minimum_quantity` > 0)),
  CONSTRAINT `chk_product_prices_sale_price` CHECK ((`sale_price` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_units` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `product_id` bigint unsigned NOT NULL,
  `unit_id` bigint unsigned NOT NULL,
  `conversion_rate` decimal(18,6) NOT NULL DEFAULT '1.000000',
  `is_base_unit` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_product_units_product_unit` (`product_id`,`unit_id`),
  KEY `idx_product_units_unit` (`unit_id`),
  CONSTRAINT `fk_product_units_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_product_units_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_product_units_conversion_rate` CHECK ((`conversion_rate` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `products` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `category_id` bigint unsigned DEFAULT NULL,
  `base_unit_id` bigint unsigned NOT NULL,
  `default_tax_activity_group_id` bigint unsigned DEFAULT NULL,
  `product_code` varchar(50) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `description` text,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_products_business_code` (`business_id`,`product_code`),
  KEY `fk_products_base_unit` (`base_unit_id`),
  KEY `idx_products_business_name` (`business_id`,`product_name`),
  KEY `idx_products_category` (`category_id`),
  KEY `idx_products_default_tax_activity_group` (`default_tax_activity_group_id`),
  CONSTRAINT `fk_products_base_unit` FOREIGN KEY (`base_unit_id`) REFERENCES `units` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_products_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_products_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_products_default_tax_activity_group` FOREIGN KEY (`default_tax_activity_group_id`) REFERENCES `tax_activity_groups` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `report_template_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `report_template_id` bigint unsigned NOT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `version_number` varchar(30) NOT NULL,
  `template_schema` json NOT NULL,
  `effective_from` date NOT NULL,
  `effective_to` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_template_versions_number` (`report_template_id`,`version_number`),
  KEY `fk_report_template_versions_created_by` (`created_by`),
  KEY `idx_report_template_versions_effective` (`report_template_id`,`effective_from`,`effective_to`),
  CONSTRAINT `fk_report_template_versions_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_report_template_versions_template` FOREIGN KEY (`report_template_id`) REFERENCES `report_templates` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_report_template_versions_period` CHECK (((`effective_to` is null) or (`effective_to` >= `effective_from`))),
  CONSTRAINT `chk_report_template_versions_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'ACTIVE',_utf8mb4'INACTIVE')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `report_templates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_by` bigint unsigned DEFAULT NULL,
  `template_code` varchar(50) NOT NULL,
  `template_name` varchar(255) NOT NULL,
  `template_type` varchar(30) NOT NULL,
  `official_form_code` varchar(50) DEFAULT NULL,
  `legal_basis` varchar(255) DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_templates_code` (`template_code`),
  KEY `fk_report_templates_created_by` (`created_by`),
  KEY `idx_report_templates_type` (`template_type`,`status`),
  CONSTRAINT `fk_report_templates_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_report_templates_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'INACTIVE'))),
  CONSTRAINT `chk_report_templates_type` CHECK ((`template_type` in (_utf8mb4'ACCOUNTING_BOOK',_utf8mb4'REPORT')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `roles` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `role_code` varchar(30) NOT NULL,
  `role_name` varchar(100) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_roles_role_code` (`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sales_order_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sales_order_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `unit_id` bigint unsigned NOT NULL,
  `tax_activity_group_id` bigint unsigned DEFAULT NULL,
  `quantity` decimal(18,3) NOT NULL,
  `conversion_rate` decimal(18,6) NOT NULL DEFAULT '1.000000',
  `base_quantity` decimal(18,3) NOT NULL,
  `unit_price` decimal(18,2) NOT NULL,
  `line_total` decimal(18,2) NOT NULL,
  `vat_calculation_rate` decimal(7,4) DEFAULT NULL,
  `pit_calculation_rate` decimal(7,4) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_order_items_line` (`sales_order_id`,`product_id`,`unit_id`),
  KEY `idx_sales_order_items_product` (`product_id`),
  KEY `idx_sales_order_items_unit` (`unit_id`),
  KEY `idx_sales_order_items_tax_activity_group` (`tax_activity_group_id`),
  CONSTRAINT `fk_sales_order_items_order` FOREIGN KEY (`sales_order_id`) REFERENCES `sales_orders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_order_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_order_items_tax_activity_group` FOREIGN KEY (`tax_activity_group_id`) REFERENCES `tax_activity_groups` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_order_items_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_sales_order_items_base_quantity` CHECK ((`base_quantity` > 0)),
  CONSTRAINT `chk_sales_order_items_conversion_rate` CHECK ((`conversion_rate` > 0)),
  CONSTRAINT `chk_sales_order_items_line_total` CHECK ((`line_total` >= 0)),
  CONSTRAINT `chk_sales_order_items_pit_rate` CHECK (((`pit_calculation_rate` is null) or ((`pit_calculation_rate` >= 0) and (`pit_calculation_rate` <= 100)))),
  CONSTRAINT `chk_sales_order_items_quantity` CHECK ((`quantity` > 0)),
  CONSTRAINT `chk_sales_order_items_unit_price` CHECK ((`unit_price` >= 0)),
  CONSTRAINT `chk_sales_order_items_vat_rate` CHECK (((`vat_calculation_rate` is null) or ((`vat_calculation_rate` >= 0) and (`vat_calculation_rate` <= 100))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sales_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `customer_id` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  `confirmed_by` bigint unsigned DEFAULT NULL,
  `order_code` varchar(50) NOT NULL,
  `source` varchar(20) NOT NULL DEFAULT 'AT_COUNTER',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `total_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `paid_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `debt_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `note` varchar(500) DEFAULT NULL,
  `confirmed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sales_orders_business_code` (`business_id`,`order_code`),
  KEY `idx_sales_orders_business_created_at` (`business_id`,`created_at`),
  KEY `idx_sales_orders_business_status` (`business_id`,`status`),
  KEY `idx_sales_orders_customer` (`customer_id`),
  KEY `idx_sales_orders_created_by` (`created_by`),
  KEY `idx_sales_orders_confirmed_by` (`confirmed_by`),
  CONSTRAINT `fk_sales_orders_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_orders_confirmed_by` FOREIGN KEY (`confirmed_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_orders_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_orders_customer` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_sales_orders_debt_amount` CHECK ((`debt_amount` >= 0)),
  CONSTRAINT `chk_sales_orders_paid_amount` CHECK ((`paid_amount` >= 0)),
  CONSTRAINT `chk_sales_orders_payment_balance` CHECK (((`paid_amount` + `debt_amount`) = `total_amount`)),
  CONSTRAINT `chk_sales_orders_source` CHECK ((`source` in (_utf8mb4'AT_COUNTER',_utf8mb4'AI'))),
  CONSTRAINT `chk_sales_orders_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'CONFIRMED',_utf8mb4'REJECTED',_utf8mb4'CANCELLED'))),
  CONSTRAINT `chk_sales_orders_total_amount` CHECK ((`total_amount` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `stock_import_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `stock_import_id` bigint unsigned NOT NULL,
  `product_id` bigint unsigned NOT NULL,
  `unit_id` bigint unsigned NOT NULL,
  `quantity` decimal(18,3) NOT NULL,
  `conversion_rate` decimal(18,6) NOT NULL DEFAULT '1.000000',
  `base_quantity` decimal(18,3) NOT NULL,
  `purchase_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `line_total` decimal(18,2) NOT NULL DEFAULT '0.00',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stock_import_items_line` (`stock_import_id`,`product_id`,`unit_id`),
  KEY `idx_stock_import_items_product` (`product_id`),
  KEY `idx_stock_import_items_unit` (`unit_id`),
  CONSTRAINT `fk_stock_import_items_import` FOREIGN KEY (`stock_import_id`) REFERENCES `stock_imports` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_import_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_import_items_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_stock_import_items_base_quantity` CHECK ((`base_quantity` > 0)),
  CONSTRAINT `chk_stock_import_items_conversion_rate` CHECK ((`conversion_rate` > 0)),
  CONSTRAINT `chk_stock_import_items_line_total` CHECK ((`line_total` >= 0)),
  CONSTRAINT `chk_stock_import_items_purchase_price` CHECK ((`purchase_price` >= 0)),
  CONSTRAINT `chk_stock_import_items_quantity` CHECK ((`quantity` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `stock_imports` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  `import_code` varchar(50) NOT NULL,
  `import_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `total_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `note` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stock_imports_business_code` (`business_id`,`import_code`),
  KEY `idx_stock_imports_business_date` (`business_id`,`import_date`),
  KEY `idx_stock_imports_created_by` (`created_by`),
  CONSTRAINT `fk_stock_imports_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_imports_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_stock_imports_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'CONFIRMED',_utf8mb4'CANCELLED'))),
  CONSTRAINT `chk_stock_imports_total_amount` CHECK ((`total_amount` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subscription_plans` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_code` varchar(30) NOT NULL,
  `plan_name` varchar(100) NOT NULL,
  `monthly_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `annual_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `description` varchar(500) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_subscription_plans_plan_code` (`plan_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subscriptions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `plan_id` bigint unsigned NOT NULL,
  `billing_cycle` varchar(20) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_subscriptions_business_id` (`business_id`),
  KEY `idx_subscriptions_plan_id` (`plan_id`),
  CONSTRAINT `fk_subscriptions_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_subscriptions_plan` FOREIGN KEY (`plan_id`) REFERENCES `subscription_plans` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `system_configurations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `updated_by` bigint unsigned DEFAULT NULL,
  `config_key` varchar(100) NOT NULL,
  `config_value` json NOT NULL,
  `data_type` varchar(20) NOT NULL DEFAULT 'JSON',
  `description` varchar(500) DEFAULT NULL,
  `is_public` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_configurations_key` (`config_key`),
  KEY `idx_system_configurations_updated_by` (`updated_by`),
  CONSTRAINT `fk_system_configurations_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_system_configurations_data_type` CHECK ((`data_type` in (_utf8mb4'STRING',_utf8mb4'NUMBER',_utf8mb4'BOOLEAN',_utf8mb4'JSON')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tax_activity_groups` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `activity_code` varchar(30) NOT NULL,
  `activity_name` varchar(255) NOT NULL,
  `vat_calculation_rate` decimal(7,4) NOT NULL DEFAULT '0.0000',
  `pit_calculation_rate` decimal(7,4) NOT NULL DEFAULT '0.0000',
  `effective_from` date NOT NULL,
  `effective_to` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tax_activity_groups_code_from` (`activity_code`,`effective_from`),
  KEY `fk_tax_activity_groups_created_by` (`created_by`),
  KEY `idx_tax_activity_groups_lookup` (`activity_code`,`status`,`effective_from`,`effective_to`),
  CONSTRAINT `fk_tax_activity_groups_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_tax_activity_groups_period` CHECK (((`effective_to` is null) or (`effective_to` >= `effective_from`))),
  CONSTRAINT `chk_tax_activity_groups_pit_rate` CHECK (((`pit_calculation_rate` >= 0) and (`pit_calculation_rate` <= 100))),
  CONSTRAINT `chk_tax_activity_groups_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'INACTIVE'))),
  CONSTRAINT `chk_tax_activity_groups_vat_rate` CHECK (((`vat_calculation_rate` >= 0) and (`vat_calculation_rate` <= 100)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tax_obligations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned NOT NULL,
  `tax_type_id` bigint unsigned NOT NULL,
  `obligation_code` varchar(50) NOT NULL,
  `period_from` date NOT NULL,
  `period_to` date NOT NULL,
  `document_number` varchar(100) DEFAULT NULL,
  `document_date` date DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `taxable_revenue` decimal(18,2) NOT NULL DEFAULT '0.00',
  `tax_rate` decimal(7,4) DEFAULT NULL,
  `tax_amount` decimal(18,2) NOT NULL,
  `due_date` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tax_obligations_business_code` (`business_id`,`obligation_code`),
  KEY `fk_tax_obligations_tax_type` (`tax_type_id`),
  KEY `fk_tax_obligations_created_by` (`created_by`),
  KEY `idx_tax_obligations_period` (`business_id`,`tax_type_id`,`period_from`,`period_to`),
  KEY `idx_tax_obligations_due_date` (`business_id`,`due_date`,`status`),
  CONSTRAINT `fk_tax_obligations_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tax_obligations_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tax_obligations_tax_type` FOREIGN KEY (`tax_type_id`) REFERENCES `tax_types` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_tax_obligations_amount` CHECK ((`tax_amount` >= 0)),
  CONSTRAINT `chk_tax_obligations_period` CHECK ((`period_to` >= `period_from`)),
  CONSTRAINT `chk_tax_obligations_rate` CHECK (((`tax_rate` is null) or ((`tax_rate` >= 0) and (`tax_rate` <= 100)))),
  CONSTRAINT `chk_tax_obligations_revenue` CHECK ((`taxable_revenue` >= 0)),
  CONSTRAINT `chk_tax_obligations_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'CONFIRMED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tax_payments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tax_obligation_id` bigint unsigned NOT NULL,
  `document_number` varchar(100) DEFAULT NULL,
  `payment_date` date NOT NULL,
  `payment_amount` decimal(18,2) NOT NULL,
  `payment_method` varchar(30) DEFAULT NULL,
  `reference_number` varchar(100) DEFAULT NULL,
  `note` varchar(500) DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_tax_payments_created_by` (`created_by`),
  KEY `idx_tax_payments_obligation_date` (`tax_obligation_id`,`payment_date`),
  KEY `idx_tax_payments_reference` (`reference_number`),
  CONSTRAINT `fk_tax_payments_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tax_payments_obligation` FOREIGN KEY (`tax_obligation_id`) REFERENCES `tax_obligations` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_tax_payments_amount` CHECK ((`payment_amount` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tax_types` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tax_code` varchar(30) NOT NULL,
  `tax_name` varchar(150) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tax_types_code` (`tax_code`),
  CONSTRAINT `chk_tax_types_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'INACTIVE')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `units` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `unit_code` varchar(30) NOT NULL,
  `unit_name` varchar(100) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_units_unit_code` (`unit_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `business_id` bigint unsigned DEFAULT NULL,
  `role_id` bigint unsigned NOT NULL,
  `username` varchar(100) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `full_name` varchar(150) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `national_id` varchar(20) DEFAULT NULL,
  `join_date` date DEFAULT NULL,
  `position` varchar(100) DEFAULT NULL,
  `termination_date` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `last_login_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_username` (`username`),
  KEY `idx_users_business_id` (`business_id`),
  KEY `idx_users_role_id` (`role_id`),
  CONSTRAINT `fk_users_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_users_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
